[package]
name = "solana-rpc-client"
version = "0.1.0"
authors = ["tikhono <tikhonov.andrii.m@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.4", features = ["json"]}
tokio = {version = "1.7.1", features = ["full"] }
solana-sdk = "1.7.4"
async-trait = "0.1.50"
serde_json = "1.0.64"
serde = "1.0.126"
bs58 = "0.4.0"
